define("loader/manifest",
	   [],
	   function () {
           return [
               {id: "bricksIMG",
                src: "images/bricks.png"},
               {id: "concreteIMG",
                src: "images/concrete.png"},
               {id: "emptyIMG",
                src: "images/empty.png"},
               {id: "bombIMG",
                src: "images/bomb.png"},
               {id: "flamesIMG",
                src: "images/flames.png"},
               {id: "characterIMG",
                src: "images/character.png"},
               {id: "character_deadIMG",
                src: "images/characterKilled.png"},
               {id: "goomba0IMG",
                src: "images/goombaLevel0.png"},
               {id: "goomba1IMG",
                src: "images/goombaLevel1.png"},
               {id: "goomba2IMG",
                src: "images/goombaLevel2.png"},
               {id: "goomba3IMG",
                src: "images/goombaLevel3.png"},
               {id: "goomba4IMG",
                src: "images/goombaLevel4.png"},
               {id: "goomba5IMG",
                src: "images/goombaLevel5.png"},
               {id: "goomba6IMG",
                src: "images/goombaLevel6.png"},
               {id: "goomba7IMG",
                src: "images/goombaLevel7.png"},
               {id: "goomba_deadIMG",
                src: "images/goombaKilled.png"},
               {id: "addBombIMG",
                src: "images/addBomb.png"},
               {id: "increaseRangeIMG",
                src: "images/increaseRange.png"},
               {id: "speedIMG",
                src: "images/speed.png"},
               {id: "detonatorIMG",
                src: "images/detonator.png"},
               {id: "bombpassIMG",
                src: "images/bombpass.png"},
               {id: "wallpassIMG",
                src: "images/wallpass.png"},
               {id: "flamepassIMG",
                src: "images/flamepass.png"},
               {id: "mystery",
                src: "images/mystery.png"},
               {id: "doorIMG",
                src: "images/door.png"},
               {id: "door_openedIMG",
                src: "images/doorOpened.png"}
		   ];
	   }
);
