define({
    SQUARE_WIDTH: 50,
    SQUARE_HEIGHT: 50,
    ROWS: 13,
    COLS: 31,
    BRICKS_SRC: "images/bricks.png",
    CONCRETE_SRC: "images/concrete.png",
    EMPTY_SRC: "images/empty.png",
    CHARACTER_SRC: "images/character.png",
    CHARACTER_DEAD_SRC: "images/characterKilled.png",
    BOMB_SRC: "images/bomb.png",
    FLAMES_SRC: "images/flames.png",
    CHARACTER_WIDTH: 40,
    CHARACTER_HEIGHT: 40,
    CHARACTER_INITIAL_X: 55,
    CHARACTER_INITIAL_Y: 55,
    BOMB_TIMEOUT: 2000,
    FLAMES_TIMEOUT: 100,
    GOOMBA_TIMEOUT: 1000,
    GOOMBA_WIDTH: 40,
    GOOMBA_HEIGHT: 40,
    GOOMBAS: [{SRC: "images/goombaLevel0.png",
               DEAD_SRC: "images/goombaLevel0Killed.png",
               BASE_SPEED: 2,
               PR_TURN: 0.5,
               PR_TURN_BACK: 0.1,
               WALLPASS: false},

              {SRC: "images/goombaLevel1.png",
               DEAD_SRC: "images/goombaLevel1Killed.png",
               BASE_SPEED: 3,
               PR_TURN: 0.5,
               PR_TURN_BACK: 0.1,
               WALLPASS: false},

              {SRC: "images/goombaLevel2.png",
               DEAD_SRC: "images/goombaLevel2Killed.png",
               BASE_SPEED: 3,
               PR_TURN: 0.2,
               PR_TURN_BACK: 0.01,
               WALLPASS: false},

              {SRC: "images/goombaLevel3.png",
               DEAD_SRC: "images/goombaLevel3Killed.png",
               BASE_SPEED: 5,
               PR_TURN: 0.5,
               PR_TURN_BACK: 0.1,
               WALLPASS: false},

              {SRC: "images/goombaLevel4.png",
               DEAD_SRC: "images/goombaLevel4Killed.png",
               BASE_SPEED: 1,
               PR_TURN: 0.6,
               PR_TURN_BACK: 0.1,
               WALLPASS: true},

              {SRC: "images/goombaLevel5.png",
               DEAD_SRC: "images/goombaLevel5Killed.png",
               BASE_SPEED: 2,
               PR_TURN: 0.5,
               PR_TURN_BACK: 0.1,
               WALLPASS: true},

              {SRC: "images/goombaLevel6.png",
               DEAD_SRC: "images/goombaLevel6Killed.png",
               BASE_SPEED: 5,
               PR_TURN: 0.7,
               PR_TURN_BACK: 0.1,
               WALLPASS: false},

              {SRC: "images/goombaLevel7.png",
               DEAD_SRC: "images/goombaLevel7Killed.png",
               BASE_SPEED: 5,
               PR_TURN: 0.7,
               PR_TURN_BACK: 0.1,
               WALLPASS: true}],

    GAMEOVER_TIMEOUT: 1000,
    SUCCESS_TIMEOUT: 1000,
    DOOR_SRC: "images/door.png",
    TOPMARGIN: 40,
    ADDBOMB_SRC: "images/addBomb.png",
    INCREASERANGE_SRC: "images/increaseRange.png",
    SPEED_SRC: "images/speed.png",
    DETONATOR_SRC: "images/detonator.png",
    BASE_PAPER_WIDTH: 1000,
    BASE_PAPER_HEIGHT: 560
});
